
FROM maven:latest AS build
# Use an official Java runtime as the base image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

COPY pom.xml ./
COPY src ./src

# Copy the application's JAR file into the container
COPY target/expense_reimbursement_system-0.0.1-SNAPSHOT.jar app.jar

# Expose the application port
EXPOSE 9090

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
