version: '3.8'

services:
  app:
    build:
      dockerfile: DOCKERFILE
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/expense_reimbursement_system_2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mysql:9.1.0
    container_name: mysql-container
    ports:
      - "9090:9090"
    environment:
      MYSQL_DATABASE: expense_reimbursement_system_2
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
